### ISSUE TITLE
Error: Cannot destructure property 'status' of 'undefined' as it is undefined.

### ISSUE THREAD

**Issue by rlardy-ulule** [SonicGarden/rspec-report-action#41]
Hi,

I want to use this action for basic Rspec report but when I try to use it I have this error :

`Error: Cannot destructure property 'status' of 'undefined' as it is undefined.`

Here is the action as declared in my workflow :

```
      - name: RSpec Report
        uses: SonicGarden/rspec-report-action@v6
        with:
          json-path: ${{ github.workspace }}/coverage/resultset.json
```

I checked that the file is present and a valid JSON.

Have I missed something ?

Thanks in advance.
